//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//


package test.gps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bankingFeeId",
    "settlementDate",
    "card",
    "agencyAccount",
    "abId",
    "desc",
    "amt"
})
public class AgencyBankingFee {

    @XmlElement(name = "BankingFeeId")
    @XmlSchemaType(name = "unsignedInt")
    protected long bankingFeeId;
    @XmlElement(name = "SettlementDate", required = true)
    protected String settlementDate;
    @XmlElement(name = "Card", required = true)
    protected Card card;
    @XmlElement(name = "AgencyAccount", required = true)
    protected ABAccount agencyAccount;
    @XmlElement(name = "AbId")
    @XmlSchemaType(name = "unsignedInt")
    protected long abId;
    @XmlElement(name = "Desc", required = true)
    protected String desc;
    @XmlElement(name = "Amt", required = true)
    protected ABDirectionAmount amt;
    private long id;

    /**
     * Gets the value of the bankingFeeId property.
     * 
     */
    public long getBankingFeeId() {
        return bankingFeeId;
    }

    /**
     * Sets the value of the bankingFeeId property.
     * 
     */
    public void setBankingFeeId(long value) {
        this.bankingFeeId = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDate(String value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link Card }
     *     
     */
    public Card getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link Card }
     *     
     */
    public void setCard(Card value) {
        this.card = value;
    }

    /**
     * Gets the value of the agencyAccount property.
     * 
     * @return
     *     possible object is
     *     {@link ABAccount }
     *     
     */
    public ABAccount getAgencyAccount() {
        return agencyAccount;
    }

    /**
     * Sets the value of the agencyAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABAccount }
     *     
     */
    public void setAgencyAccount(ABAccount value) {
        this.agencyAccount = value;
    }

    /**
     * Gets the value of the abId property.
     * 
     */
    public long getAbId() {
        return abId;
    }

    /**
     * Sets the value of the abId property.
     * 
     */
    public void setAbId(long value) {
        this.abId = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the amt property.
     * 
     * @return
     *     possible object is
     *     {@link ABDirectionAmount }
     *     
     */
    public ABDirectionAmount getAmt() {
        return amt;
    }

    /**
     * Sets the value of the amt property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABDirectionAmount }
     *     
     */
    public void setAmt(ABDirectionAmount value) {
        this.amt = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }

}
