//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//


package test.gps;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordType",
    "chgbackRepresId",
    "localDate",
    "settlementDate",
    "card",
    "account",
    "txnCode",
    "txnAmt",
    "cashbackAmt",
    "billAmt",
    "apprCode",
    "trace",
    "merchCode",
    "term",
    "schema",
    "txn",
    "msgSource",
    "repeat",
    "settlementAmt",
    "fee",
    "arn",
    "fiid",
    "riid",
    "reasonCode",
    "classification",
    "origTxnAmt",
    "partialReversal"
})
public class CardChrgBackRepRes {

    @XmlElement(name = "RecordType", required = true)
    protected String recordType;
    @XmlElement(name = "ChgbackRepresId")
    @XmlSchemaType(name = "unsignedInt")
    protected long chgbackRepresId;
    @XmlElement(name = "LocalDate", required = true)
    protected String localDate;
    @XmlElement(name = "SettlementDate", required = true)
    protected String settlementDate;
    @XmlElement(name = "Card", required = true)
    protected Card card;
    @XmlElement(name = "Account", required = true)
    protected AccountChrgBack account;
    @XmlElement(name = "TxnCode", required = true)
    protected TxnCode txnCode;
    @XmlElement(name = "TxnAmt", required = true)
    protected BasicAmount txnAmt;
    @XmlElement(name = "CashbackAmt", required = true)
    protected BasicAmount cashbackAmt;
    @XmlElement(name = "BillAmt", required = true)
    protected RateAmount billAmt;
    @XmlElement(name = "ApprCode", required = true)
    protected String apprCode;
    @XmlElement(name = "Trace", required = true)
    protected Trace trace;
    @XmlElement(name = "MerchCode", required = true)
    protected String merchCode;
    @XmlElement(name = "Term", required = true)
    protected Term term;
    @XmlElement(name = "Schema", required = true)
    @XmlSchemaType(name = "string")
    protected Schema schema;
    @XmlElement(name = "Txn", required = true)
    protected Txn txn;
    @XmlElement(name = "MsgSource", required = true)
    protected MsgSource msgSource;
    @XmlElement(name = "Repeat")
    protected short repeat;
    @XmlElement(name = "SettlementAmt", required = true)
    protected SettlementAmt settlementAmt;
    @XmlElement(name = "Fee", required = true)
    protected DirectionAmount fee;
    @XmlElement(name = "ARN", required = true)
    protected String arn;
    @XmlElement(name = "FIID", required = true)
    protected String fiid;
    @XmlElement(name = "RIID", required = true)
    protected String riid;
    @XmlElement(name = "ReasonCode", required = true)
    protected String reasonCode;
    @XmlElement(name = "Classification", required = true)
    protected Classification classification;
    @XmlElementRef(name = "OrigTxnAmt", type = JAXBElement.class, required = false)
    protected JAXBElement<PartialAmount> origTxnAmt;
    @XmlElementRef(name = "PartialReversal", type = JAXBElement.class, required = false)
    protected JAXBElement<Boolean> partialReversal;
    private long id;

    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordType(String value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the chgbackRepresId property.
     * 
     */
    public long getChgbackRepresId() {
        return chgbackRepresId;
    }

    /**
     * Sets the value of the chgbackRepresId property.
     * 
     */
    public void setChgbackRepresId(long value) {
        this.chgbackRepresId = value;
    }

    /**
     * Gets the value of the localDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalDate() {
        return localDate;
    }

    /**
     * Sets the value of the localDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalDate(String value) {
        this.localDate = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDate(String value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link Card }
     *     
     */
    public Card getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link Card }
     *     
     */
    public void setCard(Card value) {
        this.card = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link AccountChrgBack }
     *     
     */
    public AccountChrgBack getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountChrgBack }
     *     
     */
    public void setAccount(AccountChrgBack value) {
        this.account = value;
    }

    /**
     * Gets the value of the txnCode property.
     * 
     * @return
     *     possible object is
     *     {@link TxnCode }
     *     
     */
    public TxnCode getTxnCode() {
        return txnCode;
    }

    /**
     * Sets the value of the txnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnCode }
     *     
     */
    public void setTxnCode(TxnCode value) {
        this.txnCode = value;
    }

    /**
     * Gets the value of the txnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getTxnAmt() {
        return txnAmt;
    }

    /**
     * Sets the value of the txnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setTxnAmt(BasicAmount value) {
        this.txnAmt = value;
    }

    /**
     * Gets the value of the cashbackAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getCashbackAmt() {
        return cashbackAmt;
    }

    /**
     * Sets the value of the cashbackAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setCashbackAmt(BasicAmount value) {
        this.cashbackAmt = value;
    }

    /**
     * Gets the value of the billAmt property.
     * 
     * @return
     *     possible object is
     *     {@link RateAmount }
     *     
     */
    public RateAmount getBillAmt() {
        return billAmt;
    }

    /**
     * Sets the value of the billAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateAmount }
     *     
     */
    public void setBillAmt(RateAmount value) {
        this.billAmt = value;
    }

    /**
     * Gets the value of the apprCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprCode() {
        return apprCode;
    }

    /**
     * Sets the value of the apprCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprCode(String value) {
        this.apprCode = value;
    }

    /**
     * Gets the value of the trace property.
     * 
     * @return
     *     possible object is
     *     {@link Trace }
     *     
     */
    public Trace getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trace }
     *     
     */
    public void setTrace(Trace value) {
        this.trace = value;
    }

    /**
     * Gets the value of the merchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCode() {
        return merchCode;
    }

    /**
     * Sets the value of the merchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCode(String value) {
        this.merchCode = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link Term }
     *     
     */
    public Term getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link Term }
     *     
     */
    public void setTerm(Term value) {
        this.term = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link Schema }
     *     
     */
    public Schema getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schema }
     *     
     */
    public void setSchema(Schema value) {
        this.schema = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link Txn }
     *     
     */
    public Txn getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Txn }
     *     
     */
    public void setTxn(Txn value) {
        this.txn = value;
    }

    /**
     * Gets the value of the msgSource property.
     * 
     * @return
     *     possible object is
     *     {@link MsgSource }
     *     
     */
    public MsgSource getMsgSource() {
        return msgSource;
    }

    /**
     * Sets the value of the msgSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgSource }
     *     
     */
    public void setMsgSource(MsgSource value) {
        this.msgSource = value;
    }

    /**
     * Gets the value of the repeat property.
     * 
     */
    public short getRepeat() {
        return repeat;
    }

    /**
     * Sets the value of the repeat property.
     * 
     */
    public void setRepeat(short value) {
        this.repeat = value;
    }

    /**
     * Gets the value of the settlementAmt property.
     * 
     * @return
     *     possible object is
     *     {@link SettlementAmt }
     *     
     */
    public SettlementAmt getSettlementAmt() {
        return settlementAmt;
    }

    /**
     * Sets the value of the settlementAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link SettlementAmt }
     *     
     */
    public void setSettlementAmt(SettlementAmt value) {
        this.settlementAmt = value;
    }

    /**
     * Gets the value of the fee property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionAmount }
     *     
     */
    public DirectionAmount getFee() {
        return fee;
    }

    /**
     * Sets the value of the fee property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionAmount }
     *     
     */
    public void setFee(DirectionAmount value) {
        this.fee = value;
    }

    /**
     * Gets the value of the arn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARN() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARN(String value) {
        this.arn = value;
    }

    /**
     * Gets the value of the fiid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFIID() {
        return fiid;
    }

    /**
     * Sets the value of the fiid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFIID(String value) {
        this.fiid = value;
    }

    /**
     * Gets the value of the riid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRIID() {
        return riid;
    }

    /**
     * Sets the value of the riid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRIID(String value) {
        this.riid = value;
    }

    /**
     * Gets the value of the reasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReasonCode() {
        return reasonCode;
    }

    /**
     * Sets the value of the reasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReasonCode(String value) {
        this.reasonCode = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link Classification }
     *     
     */
    public Classification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classification }
     *     
     */
    public void setClassification(Classification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the origTxnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PartialAmount }{@code >}
     *     
     */
    public JAXBElement<PartialAmount> getOrigTxnAmt() {
        return origTxnAmt;
    }

    /**
     * Sets the value of the origTxnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PartialAmount }{@code >}
     *     
     */
    public void setOrigTxnAmt(JAXBElement<PartialAmount> value) {
        this.origTxnAmt = value;
    }

    /**
     * Gets the value of the partialReversal property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public JAXBElement<Boolean> getPartialReversal() {
        return partialReversal;
    }

    /**
     * Sets the value of the partialReversal property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     *     
     */
    public void setPartialReversal(JAXBElement<Boolean> value) {
        this.partialReversal = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }

}
