//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//


package test.gps;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recType",
    "authId",
    "authTxnID",
    "localDate",
    "settlementDate",
    "card",
    "account",
    "txnCode",
    "txnAmt",
    "cashbackAmt",
    "billAmt",
    "apprCode",
    "trace",
    "merchCode",
    "term",
    "schema",
    "txn",
    "msgSource",
    "paddingAmt",
    "rateFee",
    "fixedFee",
    "commissionAmt",
    "classification",
    "response",
    "origTxnAmt",
    "reversalReason"
})
public class CardAuthorisation {

    @XmlElement(name = "RecType", required = true)
    @XmlSchemaType(name = "string")
    protected RecType recType;
    @XmlElement(name = "AuthId")
    @XmlSchemaType(name = "unsignedInt")
    protected long authId;
    @XmlElement(name = "AuthTxnID")
    @XmlSchemaType(name = "unsignedInt")
    protected long authTxnID;
    @XmlElement(name = "LocalDate", required = true)
    protected String localDate;
    @XmlElement(name = "SettlementDate", required = true)
    protected String settlementDate;
    @XmlElement(name = "Card", required = true)
    protected Card card;
    @XmlElement(name = "Account", required = true)
    protected Account account;
    @XmlElement(name = "TxnCode", required = true)
    protected TxnCode txnCode;
    @XmlElement(name = "TxnAmt", required = true)
    protected BasicAmount txnAmt;
    @XmlElement(name = "CashbackAmt", required = true)
    protected BasicAmount cashbackAmt;
    @XmlElement(name = "BillAmt", required = true)
    protected RateAmount billAmt;
    @XmlElement(name = "ApprCode", required = true)
    protected String apprCode;
    @XmlElement(name = "Trace", required = true)
    protected Trace trace;
    @XmlElement(name = "MerchCode", required = true)
    protected String merchCode;
    @XmlElement(name = "Term", required = true)
    protected Term term;
    @XmlElement(name = "Schema", required = true)
    @XmlSchemaType(name = "string")
    protected Schema schema;
    @XmlElement(name = "Txn", required = true)
    protected Txn txn;
    @XmlElement(name = "MsgSource", required = true)
    protected MsgSourceCardAuthorisation msgSource;
    @XmlElement(name = "PaddingAmt", required = true)
    protected BasicAmount paddingAmt;
    @XmlElement(name = "Rate_Fee", required = true)
    protected RateFee rateFee;
    @XmlElement(name = "Fixed_Fee", required = true)
    protected FixedFee fixedFee;
    @XmlElement(name = "CommissionAmt", required = true)
    protected BasicAmount commissionAmt;
    @XmlElement(name = "Classification", required = true)
    protected Classification classification;
    @XmlElement(name = "Response", required = true)
    protected Response response;
    @XmlElementRef(name = "OrigTxnAmt", type = JAXBElement.class, required = false)
    protected JAXBElement<PartialAmount> origTxnAmt;
    @XmlElementRef(name = "ReversalReason", type = JAXBElement.class, required = false)
    protected JAXBElement<String> reversalReason;
    private long id;

    /**
     * Gets the value of the recType property.
     * 
     * @return
     *     possible object is
     *     {@link RecType }
     *     
     */
    public RecType getRecType() {
        return recType;
    }

    /**
     * Sets the value of the recType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecType }
     *     
     */
    public void setRecType(RecType value) {
        this.recType = value;
    }

    /**
     * Gets the value of the authId property.
     * 
     */
    public long getAuthId() {
        return authId;
    }

    /**
     * Sets the value of the authId property.
     * 
     */
    public void setAuthId(long value) {
        this.authId = value;
    }

    /**
     * Gets the value of the authTxnID property.
     * 
     */
    public long getAuthTxnID() {
        return authTxnID;
    }

    /**
     * Sets the value of the authTxnID property.
     * 
     */
    public void setAuthTxnID(long value) {
        this.authTxnID = value;
    }

    /**
     * Gets the value of the localDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalDate() {
        return localDate;
    }

    /**
     * Sets the value of the localDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalDate(String value) {
        this.localDate = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDate(String value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link Card }
     *     
     */
    public Card getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link Card }
     *     
     */
    public void setCard(Card value) {
        this.card = value;
    }

    /**
     * Gets the value of the account property.
     * 
     * @return
     *     possible object is
     *     {@link Account }
     *     
     */
    public Account getAccount() {
        return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *     allowed object is
     *     {@link Account }
     *     
     */
    public void setAccount(Account value) {
        this.account = value;
    }

    /**
     * Gets the value of the txnCode property.
     * 
     * @return
     *     possible object is
     *     {@link TxnCode }
     *     
     */
    public TxnCode getTxnCode() {
        return txnCode;
    }

    /**
     * Sets the value of the txnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnCode }
     *     
     */
    public void setTxnCode(TxnCode value) {
        this.txnCode = value;
    }

    /**
     * Gets the value of the txnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getTxnAmt() {
        return txnAmt;
    }

    /**
     * Sets the value of the txnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setTxnAmt(BasicAmount value) {
        this.txnAmt = value;
    }

    /**
     * Gets the value of the cashbackAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getCashbackAmt() {
        return cashbackAmt;
    }

    /**
     * Sets the value of the cashbackAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setCashbackAmt(BasicAmount value) {
        this.cashbackAmt = value;
    }

    /**
     * Gets the value of the billAmt property.
     * 
     * @return
     *     possible object is
     *     {@link RateAmount }
     *     
     */
    public RateAmount getBillAmt() {
        return billAmt;
    }

    /**
     * Sets the value of the billAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateAmount }
     *     
     */
    public void setBillAmt(RateAmount value) {
        this.billAmt = value;
    }

    /**
     * Gets the value of the apprCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprCode() {
        return apprCode;
    }

    /**
     * Sets the value of the apprCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprCode(String value) {
        this.apprCode = value;
    }

    /**
     * Gets the value of the trace property.
     * 
     * @return
     *     possible object is
     *     {@link Trace }
     *     
     */
    public Trace getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trace }
     *     
     */
    public void setTrace(Trace value) {
        this.trace = value;
    }

    /**
     * Gets the value of the merchCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCode() {
        return merchCode;
    }

    /**
     * Sets the value of the merchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCode(String value) {
        this.merchCode = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link Term }
     *     
     */
    public Term getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link Term }
     *     
     */
    public void setTerm(Term value) {
        this.term = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link Schema }
     *     
     */
    public Schema getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link Schema }
     *     
     */
    public void setSchema(Schema value) {
        this.schema = value;
    }

    /**
     * Gets the value of the txn property.
     * 
     * @return
     *     possible object is
     *     {@link Txn }
     *     
     */
    public Txn getTxn() {
        return txn;
    }

    /**
     * Sets the value of the txn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Txn }
     *     
     */
    public void setTxn(Txn value) {
        this.txn = value;
    }

    /**
     * Gets the value of the msgSource property.
     * 
     * @return
     *     possible object is
     *     {@link MsgSourceCardAuthorisation }
     *     
     */
    public MsgSourceCardAuthorisation getMsgSource() {
        return msgSource;
    }

    /**
     * Sets the value of the msgSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgSourceCardAuthorisation }
     *     
     */
    public void setMsgSource(MsgSourceCardAuthorisation value) {
        this.msgSource = value;
    }

    /**
     * Gets the value of the paddingAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getPaddingAmt() {
        return paddingAmt;
    }

    /**
     * Sets the value of the paddingAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setPaddingAmt(BasicAmount value) {
        this.paddingAmt = value;
    }

    /**
     * Gets the value of the rateFee property.
     * 
     * @return
     *     possible object is
     *     {@link RateFee }
     *     
     */
    public RateFee getRateFee() {
        return rateFee;
    }

    /**
     * Sets the value of the rateFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link RateFee }
     *     
     */
    public void setRateFee(RateFee value) {
        this.rateFee = value;
    }

    /**
     * Gets the value of the fixedFee property.
     * 
     * @return
     *     possible object is
     *     {@link FixedFee }
     *     
     */
    public FixedFee getFixedFee() {
        return fixedFee;
    }

    /**
     * Sets the value of the fixedFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixedFee }
     *     
     */
    public void setFixedFee(FixedFee value) {
        this.fixedFee = value;
    }

    /**
     * Gets the value of the commissionAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getCommissionAmt() {
        return commissionAmt;
    }

    /**
     * Sets the value of the commissionAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setCommissionAmt(BasicAmount value) {
        this.commissionAmt = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link Classification }
     *     
     */
    public Classification getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classification }
     *     
     */
    public void setClassification(Classification value) {
        this.classification = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link Response }
     *     
     */
    public Response getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link Response }
     *     
     */
    public void setResponse(Response value) {
        this.response = value;
    }

    /**
     * Gets the value of the origTxnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PartialAmount }{@code >}
     *     
     */
    public JAXBElement<PartialAmount> getOrigTxnAmt() {
        return origTxnAmt;
    }

    /**
     * Sets the value of the origTxnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PartialAmount }{@code >}
     *     
     */
    public void setOrigTxnAmt(JAXBElement<PartialAmount> value) {
        this.origTxnAmt = value;
    }

    /**
     * Gets the value of the reversalReason property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getReversalReason() {
        return reversalReason;
    }

    /**
     * Sets the value of the reversalReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setReversalReason(JAXBElement<String> value) {
        this.reversalReason = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }

}
