//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//


package test.gps;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cashType",
    "bankingId",
    "file",
    "settlementDate",
    "card",
    "agencyAccount",
    "external",
    "cashCode",
    "desc",
    "cashAmt",
    "declineReason",
    "origTxnAmt"
})
public class DeclinedAgencyBanking {

    @XmlElement(name = "CashType", required = true)
    protected String cashType;
    @XmlElement(name = "BankingId")
    @XmlSchemaType(name = "unsignedInt")
    protected long bankingId;
    @XmlElement(name = "File", required = true)
    protected ABFile file;
    @XmlElement(name = "SettlementDate", required = true)
    protected String settlementDate;
    @XmlElement(name = "Card", required = true)
    protected Card card;
    @XmlElement(name = "AgencyAccount", required = true)
    protected ABAccount agencyAccount;
    @XmlElement(name = "External", required = true)
    protected ABExternal external;
    @XmlElement(name = "CashCode", required = true)
    protected ABCashCode cashCode;
    @XmlElement(name = "Desc", required = true)
    protected String desc;
    @XmlElement(name = "CashAmt", required = true)
    protected BasicAmount cashAmt;
    @XmlElement(name = "DeclineReason", required = true, nillable = true)
    protected String declineReason;
    @XmlElementRef(name = "OrigTxnAmt", type = JAXBElement.class, required = false)
    protected JAXBElement<PartialAmount> origTxnAmt;
    private long id;

    /**
     * Gets the value of the cashType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCashType() {
        return cashType;
    }

    /**
     * Sets the value of the cashType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCashType(String value) {
        this.cashType = value;
    }

    /**
     * Gets the value of the bankingId property.
     * 
     */
    public long getBankingId() {
        return bankingId;
    }

    /**
     * Sets the value of the bankingId property.
     * 
     */
    public void setBankingId(long value) {
        this.bankingId = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link ABFile }
     *     
     */
    public ABFile getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABFile }
     *     
     */
    public void setFile(ABFile value) {
        this.file = value;
    }

    /**
     * Gets the value of the settlementDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettlementDate() {
        return settlementDate;
    }

    /**
     * Sets the value of the settlementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettlementDate(String value) {
        this.settlementDate = value;
    }

    /**
     * Gets the value of the card property.
     * 
     * @return
     *     possible object is
     *     {@link Card }
     *     
     */
    public Card getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     * 
     * @param value
     *     allowed object is
     *     {@link Card }
     *     
     */
    public void setCard(Card value) {
        this.card = value;
    }

    /**
     * Gets the value of the agencyAccount property.
     * 
     * @return
     *     possible object is
     *     {@link ABAccount }
     *     
     */
    public ABAccount getAgencyAccount() {
        return agencyAccount;
    }

    /**
     * Sets the value of the agencyAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABAccount }
     *     
     */
    public void setAgencyAccount(ABAccount value) {
        this.agencyAccount = value;
    }

    /**
     * Gets the value of the external property.
     * 
     * @return
     *     possible object is
     *     {@link ABExternal }
     *     
     */
    public ABExternal getExternal() {
        return external;
    }

    /**
     * Sets the value of the external property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABExternal }
     *     
     */
    public void setExternal(ABExternal value) {
        this.external = value;
    }

    /**
     * Gets the value of the cashCode property.
     * 
     * @return
     *     possible object is
     *     {@link ABCashCode }
     *     
     */
    public ABCashCode getCashCode() {
        return cashCode;
    }

    /**
     * Sets the value of the cashCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ABCashCode }
     *     
     */
    public void setCashCode(ABCashCode value) {
        this.cashCode = value;
    }

    /**
     * Gets the value of the desc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesc() {
        return desc;
    }

    /**
     * Sets the value of the desc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesc(String value) {
        this.desc = value;
    }

    /**
     * Gets the value of the cashAmt property.
     * 
     * @return
     *     possible object is
     *     {@link BasicAmount }
     *     
     */
    public BasicAmount getCashAmt() {
        return cashAmt;
    }

    /**
     * Sets the value of the cashAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link BasicAmount }
     *     
     */
    public void setCashAmt(BasicAmount value) {
        this.cashAmt = value;
    }

    /**
     * Gets the value of the declineReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeclineReason() {
        return declineReason;
    }

    /**
     * Sets the value of the declineReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeclineReason(String value) {
        this.declineReason = value;
    }

    /**
     * Gets the value of the origTxnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link PartialAmount }{@code >}
     *     
     */
    public JAXBElement<PartialAmount> getOrigTxnAmt() {
        return origTxnAmt;
    }

    /**
     * Sets the value of the origTxnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link PartialAmount }{@code >}
     *     
     */
    public void setOrigTxnAmt(JAXBElement<PartialAmount> value) {
        this.origTxnAmt = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }

}
