//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//


package test.gps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
public class Event {

    @XmlAttribute(name = "Type", required = true)
    protected EventType type;
    @XmlAttribute(name = "Source", required = true)
    @XmlSchemaType(name = "unsignedByte")
    protected short source;
    @XmlAttribute(name = "ActivationDate", required = true)
    protected String activationDate;
    @XmlAttribute(name = "ConvertedDate")
    protected String convertedDate;
    @XmlAttribute(name = "StatCode", required = true)
    protected String statCode;
    @XmlAttribute(name = "OldStatCode", required = true)
    protected String oldStatCode;
    @XmlAttribute(name = "Date", required = true)
    protected String date;
    private long id;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link EventType }
     *     
     */
    public EventType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventType }
     *     
     */
    public void setType(EventType value) {
        this.type = value;
    }

    /**
     * Gets the value of the source property.
     * 
     */
    public short getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     */
    public void setSource(short value) {
        this.source = value;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActivationDate() {
        return activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActivationDate(String value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the convertedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConvertedDate() {
        return convertedDate;
    }

    /**
     * Sets the value of the convertedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConvertedDate(String value) {
        this.convertedDate = value;
    }

    /**
     * Gets the value of the statCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatCode() {
        return statCode;
    }

    /**
     * Sets the value of the statCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatCode(String value) {
        this.statCode = value;
    }

    /**
     * Gets the value of the oldStatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldStatCode() {
        return oldStatCode;
    }

    /**
     * Sets the value of the oldStatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldStatCode(String value) {
        this.oldStatCode = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }

}
