//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//


package test.gps;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cardAuthorisationOrCardFinancialOrCardChrgBackRepRes"
})
@XmlRootElement(name = "Transactions")
public class Transactions {

    @XmlElements({
        @XmlElement(name = "CardAuthorisation", type = CardAuthorisation.class),
        @XmlElement(name = "CardFinancial", type = CardFinancial.class),
        @XmlElement(name = "CardChrgBackRepRes", type = CardChrgBackRepRes.class),
        @XmlElement(name = "CardFee", type = CardFee.class),
        @XmlElement(name = "MasterCardFee", type = MasterCardFee.class),
        @XmlElement(name = "CardLoadUnload", type = CardLoadUnload.class),
        @XmlElement(name = "ApprovedAgencyBanking", type = ApprovedAgencyBanking.class),
        @XmlElement(name = "DeclinedAgencyBanking", type = DeclinedAgencyBanking.class),
        @XmlElement(name = "AgencyBankingFee", type = AgencyBankingFee.class),
        @XmlElement(name = "CardBalAdjust", type = CardBalAdjust.class),
        @XmlElement(name = "CardEvent", type = CardEvent.class)
    })
    protected List<Object> cardAuthorisationOrCardFinancialOrCardChrgBackRepRes;
    private long id;

    /**
     * Gets the value of the cardAuthorisationOrCardFinancialOrCardChrgBackRepRes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cardAuthorisationOrCardFinancialOrCardChrgBackRepRes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCardAuthorisationOrCardFinancialOrCardChrgBackRepRes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardAuthorisation }
     * {@link CardFinancial }
     * {@link CardChrgBackRepRes }
     * {@link CardFee }
     * {@link MasterCardFee }
     * {@link CardLoadUnload }
     * {@link ApprovedAgencyBanking }
     * {@link DeclinedAgencyBanking }
     * {@link AgencyBankingFee }
     * {@link CardBalAdjust }
     * {@link CardEvent }
     * 
     * 
     */
    public List<Object> getCardAuthorisationOrCardFinancialOrCardChrgBackRepRes() {
        if (cardAuthorisationOrCardFinancialOrCardChrgBackRepRes == null) {
            cardAuthorisationOrCardFinancialOrCardChrgBackRepRes = new ArrayList<Object>();
        }
        return this.cardAuthorisationOrCardFinancialOrCardChrgBackRepRes;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }

}
