//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 05:33:39 PM EET 
//


package test.company;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "address"
})
@XmlRootElement(name = "employee")
public class Employee {

    @XmlElement(required = true)
    protected Employee.Address address;
    private long id;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Employee.Address }
     *     
     */
    public Employee.Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Employee.Address }
     *     
     */
    public void setAddress(Employee.Address value) {
        this.address = value;
    }

    public long getId() {
        return id;
    }

    public void setId(long _id) {
        id = _id;
    }


    /**
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "road"
    })
    public static class Address {

        @XmlElement(required = true)
        protected String road;
        private long id;

        /**
         * Gets the value of the road property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoad() {
            return road;
        }

        /**
         * Sets the value of the road property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoad(String value) {
            this.road = value;
        }

        public long getId() {
            return id;
        }

        public void setId(long _id) {
            id = _id;
        }

    }

}
