//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.01.23 at 07:33:04 PM EET 
//

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import test.gps.ABAccount;
import test.gps.ABCashCode;
import test.gps.ABDirectionAmount;
import test.gps.ABExternal;
import test.gps.ABFile;
import test.gps.Account;
import test.gps.AccountChrgBack;
import test.gps.AgencyBankingFee;
import test.gps.ApprovedAgencyBanking;
import test.gps.BasicAmount;
import test.gps.CCAAmount;
import test.gps.Card;
import test.gps.CardAuthorisation;
import test.gps.CardBalAdjust;
import test.gps.CardChrgBackRepRes;
import test.gps.CardEvent;
import test.gps.CardFee;
import test.gps.CardFinancial;
import test.gps.CardLoadUnload;
import test.gps.Classification;
import test.gps.DeclinedAgencyBanking;
import test.gps.DirectionAmount;
import test.gps.Event;
import test.gps.FeeClass;
import test.gps.FixedFee;
import test.gps.LoadSource;
import test.gps.MasterCardFee;
import test.gps.MasterCardFeeClass;
import test.gps.MsgSource;
import test.gps.MsgSourceCardAuthorisation;
import test.gps.ObjectFactory;
import test.gps.PartialAmount;
import test.gps.RateAmount;
import test.gps.RateFee;
import test.gps.Recon;
import test.gps.Response;
import test.gps.Settlement;
import test.gps.SettlementAmt;
import test.gps.Term;
import test.gps.Trace;
import test.gps.Transactions;
import test.gps.Txn;
import test.gps.TxnCode;

public class JAXBDebug {


    public static JAXBContext createContext(ClassLoader classLoader)
        throws JAXBException
    {
        return JAXBContext.newInstance(Transactions.class, CardAuthorisation.class, CardFinancial.class, CardChrgBackRepRes.class, CardFee.class, MasterCardFee.class, CardLoadUnload.class, ApprovedAgencyBanking.class, DeclinedAgencyBanking.class, AgencyBankingFee.class, CardBalAdjust.class, CardEvent.class, BasicAmount.class, RateAmount.class, DirectionAmount.class, PartialAmount.class, SettlementAmt.class, CCAAmount.class, FeeClass.class, MasterCardFeeClass.class, Response.class, Classification.class, MsgSource.class, MsgSourceCardAuthorisation.class, Txn.class, Term.class, Trace.class, TxnCode.class, Card.class, Account.class, AccountChrgBack.class, LoadSource.class, Recon.class, Settlement.class, ABFile.class, ABAccount.class, ABExternal.class, ABCashCode.class, ABDirectionAmount.class, Event.class, RateFee.class, FixedFee.class, ObjectFactory.class);
    }

}
